[package]
name = "py-crude-resource-monitor"
version = "0.1.4"
edition = "2021"
license = "MIT"

[features]
unwind = ["py-spy/unwind"]

[dependencies]
anyhow = "1.0.95"
clap = "4.5.26"
env_logger = "0.11.6"
log = "0.4.25"
py-spy = { version = "0.4.0" }
serde_json = "1.0.135"
sysinfo = "0.33.1"
serde = { version = "1.0.217", features = ["derive"] }
dialoguer = "0.11.0"
tokio = { version = "1.43.0", features = ["full"] }
axum = { version = "0.7.9", features = ["macros"] }
rust-embed = "8.5.0"
mime_guess = "2.0.5"
tower-http = { version = "0.6.2", features = ["cors", "fs"] }
tower = { version = "0.5.2", features = ["util"] }
snafu = { version = "0.8.5", features = ["std"] }
flate2 = "1.1.0"
base64 = "0.22.1"
users = "0.11.0"
shlex = "1.3.0"
