[package]
name = "py-crude-resource-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = "4.5.21"
env_logger = "0.11.5"
log = "0.4.22"
py-spy = { version = "0.4.0", features = ["unwind"] }
serde_json = "1.0.133"
sysinfo = "0.32.1"
serde = { version = "1.0.215", features = ["derive"] }
dialoguer = "0.11.0"
