name: Build
on:
  pull_request:
    branches:
      - "master"
  push:

jobs:
  build:
    name: Build Binary (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            unwind: true
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            unwind: true
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            unwind: false
          - target: aarch64-apple-darwin
            os: macos-latest
            unwind: false
          - target: x86_64-apple-darwin
            os: macos-13
            unwind: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install pkgconfig dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libunwind-dev build-essential -y

      - name: Build
        run: |
          cargo build --release ${{ matrix.unwind && '--features unwind' || '' }} --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/py-crude-resource-monitor
            target/${{ matrix.target }}/release/py-crude-resource-monitor.exe
